# Generated by Django 4.2 on 2023-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MenuTree',
        ),
    ]
